site_name: "yongli's blog"
site_description: "Findings, thoughts, tutorials, work. Pieces of my mind!"
site_url: "https://wkdays.github.io/b"
repo_url: "https://github.com/wkdays/b/"
repo_name: "wkdays/b"
exclude_docs: drafts/
not_in_nav: |
  notes/
  tips-for-writing-*

nav:
  - ...
  - Home: index.md
  - Posts:
    - 2024:
      - posts/a.md
      - posts/b.md
      - posts/c.md
  - AI:
    - 机器人:
      - AI/robot.md


theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference



markdown_extensions:
- admonition
- attr_list
- footnotes
- md_in_html
- meta
- pymdownx.blocks.admonition
- pymdownx.blocks.html
- pymdownx.blocks.tab
- pymdownx.details


plugins:
- search
- markdown-exec
- awesome-pages
